# Generated by Django 4.0.4 on 2022-05-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0002_alter_visitors_options_visitors_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visitors',
        ),
    ]
