# Generated by Django 4.0.4 on 2022-05-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='visitors',
        ),
    ]
